### ISSUE TITLE
Invalid meta tag is set by Foundation

### ISSUE THREAD

**Issue by wesselbaum** [foundation/foundation-sites#12167]
## Expected Behavior

When foundation is initialized `<meta class="foundation-mq">` is added which is not valid HTML according to [Nu Html Checker](https://validator.w3.org/nu/)

```
Error: Element meta is missing one or more of the following attributes: charset, content, http-equiv, itemprop, name, property.

From line 38, column 1; to line 38, column 28

xt/css">↩↩<meta class="foundation-mq"></head

Attributes for element meta:
    Global attributes
    name — Metadata name
    http-equiv — Pragma directive
    content — Value of the element
    charset — Character encoding declaration
```

## Current Behavior

The meta tag is set and not removed

## Possible Solution

Usage of another tag or removing it after javascript is initialized. 

## Test Case and/or Steps to Reproduce (for bugs)

Test Case: 

How to reproduce:
1. Start a project with foundation
2. Initialize Javascript
3. See the meta tag in head

## Context

I need my project to be valid HTML to sellt it to my customers. Since it does not validate I have to explain why, which I can't.

## Your Environment

- Foundation version(s) used: 6.6.3
- Browser(s) name and version(s): any
- Device, Operating System and version: any
- Link to your project: any

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] This is a bug report or a feature request.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by DanielRuf** [comment]
We use it to store the breakpoints.

https://www.w3.org/TR/2011/WD-html5-author-20110809/the-meta-element.html

> The meta element represents various kinds of metadata that cannot be expressed using the title, base, link, style, and script elements.

> Exactly one of the name, http-equiv, and charset attributes must be specified.

> If either name or http-equiv is specified, then the content attribute must also be specified. Otherwise, it must be omitted.

https://github.com/foundation/foundation-sites/search?q=foundation-mq

There are several solutions:
* manually add `name` and `content` in the code of foundation.js
* patch the npm package using https://www.npmjs.com/package/patch-package by applying the changes to the needed files
* ignore it for now, browsers can still display the website without any issues

PRs which fix this are very welcome. I have not much time to do this myself.

**Comment by DanielRuf** [comment]
> Usage of another tag

See
> The meta element represents various kinds of metadata that cannot be expressed using the title, base, link, style, and script elements.

> or removing it after javascript is initialized.

This would propbably cause more issues.

**Comment by Zignature** [comment]
Add `<meta name="generator" content="Zurb Foundation 6" class="foundation-mq">` to the `head` section of your website and your problem is solved :)
